---
- hosts: kube-2
  become: yes
  become_user: root
  tasks:
    - name: Disable swap now
      command: swapoff -a

    - name: Disable swap after a restart
      cron:
        name: Disable swap
        special_time: reboot
        job: "swapoff -a"

    - name: Letting iptables see bridged traffic
      shell:
        cmd: |
          cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
          br_netfilter
          EOF

          cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
          sudo sysctl --system

    - name: Install prerequisites
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl


    # TODO use an Ansible module instead
    - name: Add GPG key for Google/Kubernetes
      shell: |
        sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install prerequisites
      apt:
        update_cache: yes
        pkg:
          - kubelet=1.23.6-00
          - kubeadm=1.23.6-00
          - kubectl=1.23.6-00

    - name: Add a hold to Kube package versions
      command: sudo apt-mark hold kubelet kubeadm kubectl

    - name: Enable kubectl for Root
      shell: export KUBECONFIG=/etc/kubernetes/admin.conf # TODO this one's effect is not permanent
